name       : reportlab
version    : 3.2.0
release    : 1
source     :
    - https://pypi.python.org/packages/source/r/reportlab/reportlab-3.2.0.tar.gz#md5=79d059e797c557aed4b40c68dd6c7eae : 72e687662bd854776407b9108483561831b45546d935df8b0477708199086293
license    : GPL-2.0 # CHECK ME
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
setup      : |
    python setup.py configure
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
