name       : python-reportlab
version    : 3.5.12
release    : 6
source     :
    - https://pypi.python.org/packages/source/r/reportlab/reportlab-3.5.12.tar.gz : 7e10261065d0f926d9d83fd1f2edb8bec466f3c60b3e927ef40e2262805c069d
license    : BSD-3-Clause
component  : programming.python
summary    : The ReportLab Toolkit
description: |
    This is the ReportLab PDF Toolkit. It allows rapid creation of rich PDF documents, and also creation of charts in a variety of bitmap and vector formats.
networking : yes
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(python3)
    - python-pillow         # check
rundeps    :
    - python-pillow
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check     : |
    # There are some errors in the output when networking is not enabled but nevertheless the tests should succeed
    %python_test
    %python3_test
