name       : python-reportlab
version    : 3.5.68
release    : 9
source     :
    - https://pypi.python.org/packages/source/r/reportlab/reportlab-3.5.68.tar.gz : efef6a97e3ab49f3f40037dbf9a4166668a17cc6aaba13d5ecbabdf854a9b332
license    : BSD-3-Clause
component  : programming.python
summary    : The ReportLab Toolkit
description: |
    This is the ReportLab PDF Toolkit. It allows rapid creation of rich PDF documents, and also creation of charts in a variety of bitmap and vector formats.
networking : yes
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(python3)
    - python-pillow         # check
rundeps    :
    - python-pillow
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    # There are some errors in the output when networking is not enabled but nevertheless the tests should succeed
    %python_test
    %python3_test
