name       : python-reportlab
version    : 3.2.0
release    : 3
source     :
    - https://pypi.python.org/packages/source/r/reportlab/reportlab-3.2.0.tar.gz#md5=79d059e797c557aed4b40c68dd6c7eae : 72e687662bd854776407b9108483561831b45546d935df8b0477708199086293
license    : BSD-3-Clause
summary    : The ReportLab Toolkit
description: |
    This is the ReportLab PDF Toolkit. It allows rapid creation of rich PDF documents, and also creation of charts in a variety of bitmap and vector formats.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
