name       : python-reportlab
version    : 3.6.9
release    : 11
source     :
    - https://pypi.python.org/packages/source/r/reportlab/reportlab-3.6.9.tar.gz : 5d0cc3682456ad213150f6dbffe7d47eab737d809e517c316103376be548fb84
license    : BSD-3-Clause
component  : programming.python
summary    : The ReportLab Toolkit
description: |
    This is the ReportLab PDF Toolkit. It allows rapid creation of rich PDF documents, and also creation of charts in a variety of bitmap and vector formats.
networking : yes
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(python3)
    - python-pillow         # check
rundeps    :
    - python-pillow
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # There are some errors in the output when networking is not enabled but nevertheless the tests should succeed
    %python3_test
