name       : python-reportlab
version    : 3.2.0
release    : 5
source     :
    - https://pypi.python.org/packages/source/r/reportlab/reportlab-3.2.0.tar.gz : 72e687662bd854776407b9108483561831b45546d935df8b0477708199086293
license    : BSD-3-Clause
component  : programming.python
summary    : The ReportLab Toolkit
description: |
    This is the ReportLab PDF Toolkit. It allows rapid creation of rich PDF documents, and also creation of charts in a variety of bitmap and vector formats.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
